//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule
    {
        public int id { get; set; }
        public Nullable<int> id_subject { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public Nullable<int> cabinet { get; set; }
        public string time { get; set; }
    
        public virtual subject subject { get; set; }
        public virtual teacher teacher { get; set; }
    }
}
